datastax-java-driver {
  basic {
    load-balancing-policy {
      class = DefaultLoadBalancingPolicy
      local-datacenter = datacenter1
    }
  }

  advanced {
    load-balancing-policy {
      class = DefaultLoadBalancingPolicy
      token-aware {
        enabled = true
      }
      dc-aware {
        local-datacenter = datacenter1
        used-hosts-per-remote-dc = 0
        allow-remote-dcs-for-local-clients = false
      }
    }
  }
}
